### ISSUE TITLE
The Searchbox only searches for markdown files in the master branch, causes surprise.

### ISSUE THREAD

**Issue by hartzell** [chutsu/ditto#12]
Thanks for the neat tool.

I had trouble getting the searchbox to do what I expected and eventually tracked it down to the fact that GitHub only indexes/searches the master branch and ditto.js includes a constraint to only search markdown files.

I think it would be clearer if:

- the ditto documentation reminded us that only the master branch is searched; and
- either the language constraint is dropped or made optional or configurable.

---

I've created an orphan gh-pages branch, following the [GitHub recipe](https://help.github.com/articles/creating-project-pages-manually/).

I was confused when searching via the searchbox didn't find any of my pages.

A bit of googling reminded me that they only index the repo's default branch ("master").

Since I wasn't sure that GitHub indexed markdown files I created a perl file on the master branch, but search was unable to find it.

A quick scan of ditto.js revealed that the actual search (for "Foo") looks like this:

```
https://api.github.com/search/code?q=Foo+in:file+language:markdown+repo:hartzell/ditto-exploration
```

This doesn't find anything because of the "language:markdown" constraint.

**Comment by chutsu** [comment]
Yes, indeed ditto does have some search limitations. 

I will update the docs to make it clear it only searches in the master branch and markdown files only. Thanks for the contribution :)

Currently I'm not too keen on the search functionality, but that is what Github returns, I'll have to improve that feature when I have some time.

**Comment by chutsu** [comment]
Btw 1 cool thing I do when editing markdown files in ditto is use a python tool called LiveReload.

      pip install livereload

If you run `livereload` at the root of your repo, it detects any file changes and automatically refreshes the page. What I normally do is have browser and editor side by side, as I type and save, the content on the browser gets automatically refreshed.

    cd <your repo>
    livereload
    # serving on 127.0.0.1:35729 ...

**Comment by chutsu** [comment]
Updated docs, please tell me if that is sufficient?
