### ISSUE TITLE
Reloading index.html causes "Uncaught TypeError"

### ISSUE THREAD

**Issue by hartzell** [chutsu/ditto#13]
I have a simple site set up (gh-pages branch of https://github.com/hartzell/ditto-exploration, http://hartzell.github.io/ditto-exploration/).  The sidebar has a link at the top to return to the main page, stolen shamelessly from the ditto site.

```markdown
# [de]()
```

Using Chrome on a mac, if I go to the main page, http://hartzell.github.io/ditto-exploration/, there are no errors in the javascript console.  If I click on the 'de' link in the top of the sidebar, I get an "Uncaught TypeError message in the console.

<img width="637" alt="screen shot 2016-02-13 at 5 06 20 pm" src="https://cloud.githubusercontent.com/assets/312978/13031089/21293b10-d274-11e5-8db9-bce7dbd98306.png">

It doesn't seem to have any particularly ill effects, but seems to be a bit messy.

**Comment by chutsu** [comment]
Hmm, interesting... I can't seem to reproduce it in Firefox on Linux, even with me clicking on the 'de' link multiple times.

**Comment by chutsu** [comment]
Ok, I see the error in Chrome, I'll try and find some time to fix that. Thanks for the heads up.

**Comment by chutsu** [comment]
Hi I added a simple fix [here][link] (admittedly in the wrong branch, but its in the master now.

[link]: https://github.com/chutsu/ditto/commit/c989a151e136eeb5d664c473d72a942ed43fef50
