### ISSUE TITLE
Expandable/Collapsible Menu links

### ISSUE THREAD

**Issue by nafergo** [chutsu/ditto#16]
Im planning to use ditto for a personal notebook but I expect to have a lot of menu links. Any ideas how to get this?

**Comment by chutsu** [comment]
I'll have a think about it, sorry been busy with end of term at the moment :) bear with me

**Comment by nafergo** [comment]
I really like the simplicity, easy-to-use and deploy of ditto :) maybe use folders inside docs for submenus? like daux.io does

**Comment by chutsu** [comment]
To be honest you can easily style the menu yourself with CSS, ditto doesn't really care how you organize your docs in the docs folder, at the end of the day you list the docs manually in the `sidebar.md` so...

I'll have a look at good menu collapse options :)

**Comment by ipluser** [comment]
You can see the magicbook:
https://github.com/ipluser/magicbook

Continue to coding for magicbook now.
