### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by yourNameIsGood** [chutsu/ditto#17]
Maybe there's something wrong with the url git.io/vUWYz.

all i got is 404 from it.

curl -L http://git.io/vUWYz > install.sh && sh install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100    15  100    15    0     0      4      0  0:00:03  0:00:03 --:--:--    48
install.sh: 1: install.sh: 404:: not found

**Comment by chutsu** [comment]
Fixed, thanks :)
