### ISSUE TITLE
Ditto ver 11 not found

### ISSUE THREAD

**Issue by nwillc** [chutsu/ditto#7]
Pages using v 11 are getting:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://chutsu.github.io/ditto/ver/0.11/highlight_8.0.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://chutsu.github.io/ditto/ver/0.11/google_code.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by chutsu** [comment]
I am ceased using Highlight JS, but if you like I can add that back in?

**Comment by chutsu** [comment]
Closing, since this issue is same as #9

**Comment by chutsu** [comment]
@nwillc, as per #9 I just wanted you to know that I have added code highlighting back. If you want to enable it please use the latest version or version 0.12. You can turn on code highlighting in the index.html file, via:

    ditto.highlight_code = true;

Thanks, let me know if you found any more issues.
