### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by Orcomp** [chutsu/ditto#8]
Really like your minimalistic approach to documentation. I was wondering whether you could add a bit more information about how the search functionality is implemented in the documentation.

**Comment by Orcomp** [comment]
Investigating this a bit more (please correct me if I am wrong), the search box seems to use the native github search functionality over the current repository. (Which, if my assumptions are right, is extremely  fast and powerful. And makes perfect sense. Using the advanced search options (https://github.com/search/advanced) we could even restrict github to only search the documents that are in the "docs" folder, or files with a specific extension. Brilliant!)

**Comment by chutsu** [comment]
So sorry for not spotting this earlier, I think github emails may have been filtered. But yes it is indeed using the Github search functionality. I will try and update the docs to reflect how the search functionality works, but to be honest I don't feel like the search results are displayed as nicely as github's, there's definitely room for improvement there. :)

**Comment by Orcomp** [comment]
Excellent. I am not too worried about how pretty it looks, as long as I know it falls back on a fast and thorough service that will return all matches. Thanks.
